/**
 * Business category / sub-category slugs for Razorpay Route linked accounts (`profile.category`, `profile.subcategory`).
 * Sourced from Razorpay appendix data (HDFCDCEMI CategoryUnderstanding spreadsheet), aligned with:
 * - https://razorpay.com/docs/payments/route/integration-guide/#business-category
 * - https://razorpay.com/docs/payments/route/integration-guide/#business-sub-category
 */

export type RazorpayRouteBusinessCategoryOption = { readonly value: string; readonly label: string };

export const RAZORPAY_ROUTE_BUSINESS_CATEGORIES = [
  { value: "ecommerce", label: "Ecommerce" },
  { value: "education", label: "Education" },
  { value: "financial_services", label: "Financial Services" },
  { value: "food", label: "Food and Beverage" },
  { value: "gaming", label: "Gaming" },
  { value: "government", label: "Government Bodies" },
  { value: "healthcare", label: "Healthcare" },
  { value: "housing", label: "Housing and Real Estate" },
  { value: "it_and_software", label: "IT and Software" },
  { value: "logistics", label: "Logistics" },
  { value: "media_and_entertainment", label: "Media and Entertainment" },
  { value: "not_for_profit", label: "Not-For-Profit" },
  { value: "services", label: "Services" },
  { value: "social", label: "Social" },
  { value: "tours_and_travel", label: "Tours and Travel" },
  { value: "transport", label: "Transport" },
  { value: "utilities", label: "Utilities" },
] as const satisfies readonly RazorpayRouteBusinessCategoryOption[];

export const RAZORPAY_ROUTE_SUBCATEGORIES_BY_CATEGORY: Readonly<
  Record<string, readonly RazorpayRouteBusinessCategoryOption[]>
> = {
  "ecommerce": [
    { value: "ecommerce_marketplace", label: "Horizontal Commerce/Marketplace" },
    { value: "agriculture", label: "Agricultural products" },
    { value: "books", label: "Books and Publications" },
    { value: "electronics_and_furniture", label: "Electronics and Furniture" },
    { value: "coupons", label: "Coupons and deals" },
    { value: "rental", label: "Product Rental" },
    { value: "fashion_and_lifestyle", label: "Fashion and Lifestyle" },
    { value: "gifting", label: "Flowers and Gifts" },
    { value: "grocery", label: "Grocery" },
    { value: "baby_products", label: "Baby Care and Toys" },
    { value: "office_supplies", label: "Office Supplies" },
    { value: "wholesale", label: "Wholesale/Bulk trade" },
    { value: "religious_products", label: "Religious products" },
    { value: "pet_products", label: "Pet Care and Supplies" },
    { value: "sports_products", label: "Sports goods" },
    { value: "arts_and_collectibles", label: "Arts, crafts and collectibles" },
    { value: "sexual_wellness_products", label: "Sexual Wellness Products" },
    { value: "drop_shipping", label: "Dropshipping" },
    { value: "crypto_machinery", label: "Crypto Machinery" },
    { value: "tobacco", label: "Tobacco" },
    { value: "weapons_and_ammunitions", label: "Weapons and Ammunitions" },
    { value: "stamps_and_coins_stores", label: "Stamps & Coins Stores" },
    { value: "automobile_parts_and_equipements", label: "MOTOR VEHICLE SUPPLIES" },
    { value: "office_equipment", label: "Office, Photographic, Photocopy, and Microfilm Equipment" },
    { value: "garden_supply_stores", label: "Lawn and Garden Supply Stores" },
    { value: "household_appliance_stores", label: "Household Appliance Stores" },
    { value: "non_durable_goods", label: "NONDURABLE GOODS" },
    { value: "electrical_parts_and_equipment", label: "Electrical Parts and Equipment" },
    { value: "wig_and_toupee_shops", label: "Wig and Toupee Shops" },
    { value: "gift_novelty_and_souvenir_shops", label: "Card, Gift, Novelty, and Souvenir Shops" },
    { value: "duty_free_stores", label: "Duty Free Stores" },
    { value: "office_and_commercial_furniture", label: "Office and Commercial Furniture" },
    { value: "dry_goods", label: "Piece Goods, Notions, and Other Dry Goods" },
    { value: "books_and_publications", label: "Book Stores" },
    { value: "camera_and_photographic_stores", label: "Camera and Photographic Supply Stores" },
    { value: "meat_supply_stores", label: "Freezer, Locker Meat Provisioners" },
    { value: "leather_goods_and_luggage", label: "Leather Goods and Luggage Stores" },
    { value: "snowmobile_dealers", label: "Snowmobile Dealers" },
    { value: "men_and_boys_clothing_stores", label: "Men‚Äôs and Boy‚Äôs Clothing and Furnishings Store" },
    { value: "paint_supply_stores", label: "Varnishes, Paints, Supplies" },
    { value: "automotive_parts", label: "Automotive Parts, Accessories Stores" },
    { value: "jewellery_and_watch_stores", label: "Precious Stones and Metals,Watches and Jewelry" },
    { value: "auto_store_home_supply_stores", label: "Auto Store, Home Supply Stores" },
    { value: "tent_stores", label: "Tent and Awning Shops" },
    { value: "petroleum_and_petroleum_products", label: "Petroleum and Petroleum Products" },
    { value: "department_stores", label: "Department Stores" },
    { value: "shoe_stores_retail", label: "Shoe Stores" },
    { value: "automotive_tire_stores", label: "Automotive Tire Stores" },
    { value: "sport_apparel_stores", label: "Sports Apparel, Riding Apparel Stores" },
    { value: "chemicals_and_allied_products", label: "Chemicals and Allied Products" },
    { value: "fireplace_parts_and_accessories", label: "FIREPLACE FIREPLACE SCREENS AND ACCESSORIES STORES" },
    { value: "commercial_equipments", label: "COMMERCIAL EQUIPMENTS" },
    { value: "family_clothing_stores", label: "Family Clothing Stores" },
    { value: "fabric_and_sewing_stores", label: "Fabric, Needlework, Piece Goods, and Sewing Stores" },
    { value: "camper_recreational_and_utility_trailer_dealers", label: "Camper, Recreational and utility trailer dealers" },
    { value: "record_shops", label: "Record Shops" },
    { value: "home_supply_warehouse", label: "Home Supply Warehouse" },
    { value: "clocks_and_silverware_stores", label: "Clock, Jewelry, Watch, and Silverware Store" },
    { value: "art_supply_stores", label: "Artist Supply Stores, Craft Shops" },
    { value: "pawn_shops", label: "Pawn Shops" },
    { value: "school_supplies_and_stationery", label: "Office, School Supply, and Stationery Stores" },
    { value: "opticians_optical_goods_and_eyeglasse_stores", label: "Opticians, Optical Goods, and Eyeglasses" },
    { value: "watch_and_jewellery_repair_stores", label: "Clock, Jewelry, and Watch Repair Shops" },
    { value: "wholesale_footwear_stores", label: "Commercial Footwear" },
    { value: "antique_stores", label: "Antique Reproduction Stores" },
    { value: "plumbing_and_heating_equipment", label: "Plumbing and Heating Equipment" },
    { value: "variety_stores", label: "Variety Stores" },
    { value: "liquor_stores", label: "Package Stores, Beer, Wine, Liquor" },
    { value: "boat_dealers", label: "Boat Dealers" },
    { value: "cosmetic_stores", label: "Cosmetic Stores" },
    { value: "home_furnishing_stores", label: "Miscellaneous House Furnishing Specialty Shops" },
    { value: "telecommunication_equipment_stores", label: "Telecommunication Equipment Including Telephone Sales" },
    { value: "women_clothing", label: "Womens Ready to Wear Stores" },
    { value: "florists", label: "Florists" },
    { value: "commercial_photography_and_graphic_design_services", label: "Commercial Art, Graphics, Photography" },
    { value: "building_matrial_stores", label: "Building Materials, Lumber Stores" },
    { value: "candy_nut_confectionery_shops", label: "Candy, Nut, Confectionery Stores" },
    { value: "glass_and_wallpaper_stores", label: "Glass, Paint, Wallpaper Stores" },
    { value: "video_game_supply_stores", label: "Video Amusement Game Supplies" },
    { value: "drapery_and_window_coverings_stores", label: "Drapery, Upholstery, and Window Coverings Stores" },
    { value: "uniforms_and_commercial_clothing_stores", label: "Men‚Äôs, Women‚Äôs, and Children‚Äôs Uniforms and Commercial Clothing" },
    { value: "automotive_paint_shops", label: "Automotive Paint Shops" },
    { value: "durable_goods_stores", label: "Durable Goods not elsewhere classified" },
    { value: "fur_shops", label: "Furriers and Fur Shops" },
    { value: "industrial_supplies", label: "Industrial Supplies" },
    { value: "motorcycle_shops_and_dealers", label: "Motorcycle Shops and Dealers" },
    { value: "children_and_infants_wear_stores", label: "Children‚Äôs and Infants‚Äô Wear Stores" },
    { value: "computer_software_stores", label: "Computer Software Stores" },
    { value: "women_accessory_stores", label: "Women Accessory and Specialty Stores" },
    { value: "books_periodicals_and_newspaper", label: "Books, Periodicals and Newspapers" },
    { value: "floor_covering_stores", label: "Floor Covering Stores" },
    { value: "crystal_and_glassware_stores", label: "Crystal and Glassware Stores" },
    { value: "hardware_equipment_and_supply_stores", label: "Hardware Equipement and Supplies" },
    { value: "discount_stores", label: "Discount stores" },
    { value: "computers_peripheral_equipment_software", label: "Computers, Computer Peripheral Equipment, Software" },
    { value: "automobile_and_truck_dealers", label: "Automobile and Truck Dealers-Used Only-Sales" },
    { value: "aircraft_and_farm_equipment_dealers", label: "Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers-not elsewhere classified" },
    { value: "antique_shops_sales_and_repairs", label: "Antique Shops-Sales, Repairs, and Restoration Services" },
    { value: "bicycle_stores", label: "Bicycle Shops-Sales and Service" },
    { value: "hearing_aids_stores", label: "Hearing Aids-Sales, Service, Supply Stores" },
    { value: "music_stores", label: "Music Stores-Musical Instruments, Pianos, Sheet Music" },
    { value: "construction_materials", label: "Construction Materials-not elsewhere classified" },
    { value: "accessory_and_apparel_stores", label: "Accessory and Apparel Stores-Miscellaneous" },
    { value: "second_hand_stores", label: "SECOND HAND STORES-USED MERCHANDISE STORES" },
    { value: "fuel_dealers", label: "Fuel Dealers-Coal, Fuel Oil, Liquefied Petroleum, Wood" },
    { value: "furniture_and_home_furnishing_store", label: "Furniture and Home Furnishing store" },
  ],
  "education": [
    { value: "college", label: "College" },
    { value: "schools", label: "Schools" },
    { value: "university", label: "University" },
    { value: "professional_courses", label: "Professional Courses" },
    { value: "distance_learning", label: "Distance Learning" },
    { value: "day_care", label: "Pre-School/Day Care" },
    { value: "coaching", label: "Coaching Institute" },
    { value: "elearning", label: "E-Learning" },
    { value: "vocational_and_trade_schools", label: "SCHOOLS, TRADE AND VOCATIONAL" },
    { value: "sporting_clubs", label: "ATHLETIC FEES" },
    { value: "dance_halls_studios_and_schools", label: "Dance Halls, Studios and Schools" },
    { value: "correspondence_schools", label: "Schools, Correspondence" },
  ],
  "financial_services": [
    { value: "mutual_fund", label: "Mutual Fund" },
    { value: "lending", label: "Lending" },
    { value: "cryptocurrency", label: "Cryptocurrency" },
    { value: "insurance", label: "Insurance" },
    { value: "nbfc", label: "NBFC" },
    { value: "cooperatives", label: "Cooperatives" },
    { value: "pension_fund", label: "Pension Fund" },
    { value: "forex", label: "Forex" },
    { value: "securities", label: "Securities" },
    { value: "commodities", label: "Commodities" },
    { value: "accounting", label: "Accounting and Taxes" },
    { value: "financial_advisor", label: "Financial and Investment Advisors/Financial Advisor" },
    { value: "crowdfunding", label: "Crowdfunding Platform" },
    { value: "trading", label: "Stock Brokerage and Trading" },
    { value: "betting", label: "Betting" },
    { value: "get_rich_schemes", label: "Get Rich Schemes" },
    { value: "moneysend_funding", label: "MoneySend Funding" },
    { value: "wire_transfers_and_money_orders", label: "WIRE TRANSFER MONEY ORDER" },
    { value: "tax_preparation_services", label: "Tax Preparation Service" },
    { value: "tax_payments", label: "Tax Payments" },
    { value: "digital_goods", label: "Digital Goods-Multi-Category" },
    { value: "atms", label: "Financial Institutions-Automated Cash Disbursements" },
  ],
  "food": [
    { value: "online_food_ordering", label: "Online Food Ordering" },
    { value: "restaurant", label: "Restaurants" },
    { value: "food_court", label: "Food Courts/Corporate Cafeteria" },
    { value: "catering", label: "Catering Services" },
    { value: "alcohol", label: "Alcoholic Beverages" },
    { value: "restaurant_search_and_booking", label: "Restaurant search and reservations" },
    { value: "dairy_products", label: "Dairy Products Stores" },
    { value: "bakeries", label: "Bakeries" },
  ],
  "gaming": [
    { value: "game_developer", label: "Game developer and publisher" },
    { value: "esports", label: "E-sports" },
    { value: "online_casino", label: "Online Casino" },
    { value: "fantasy_sports", label: "Fantasy Sports" },
    { value: "gaming_marketplace", label: "Game distributor/Marketplace" },
  ],
  "government": [
    { value: "central", label: "Central Department" },
    { value: "state", label: "State Department" },
    { value: "intra_government_purchases", label: "Intra-Government Purchases -Government Only" },
    { value: "goverment_postal_services", label: "Postal Services -Government Only" },
  ],
  "healthcare": [
    { value: "pharmacy", label: "Pharmacy" },
    { value: "clinic", label: "Clinic" },
    { value: "hospital", label: "Hospital" },
    { value: "lab", label: "Lab" },
    { value: "dietician", label: "Dietician/Diet Services" },
    { value: "fitness", label: "Gym and Fitness" },
    { value: "health_coaching", label: "Health and Lifestyle Coaching" },
    { value: "health_products", label: "Health Products" },
    { value: "healthcare_marketplace", label: "Marketplace/Aggregator" },
    { value: "osteopaths", label: "Osteopaths" },
    { value: "medical_equipment_and_supply_stores", label: "Dental/Laboratory/Medical/Ophthalmic Hospital Equipment and Supplies" },
    { value: "drug_stores", label: "DRUGS, DRUG PROPRIETARIES" },
    { value: "podiatrists_and_chiropodists", label: "Podiatrists and Chiropodists" },
    { value: "dentists_and_orthodontists", label: "Dentists, Orthodontists" },
    { value: "hardware_stores", label: "Hardware Stores" },
    { value: "ophthalmologists", label: "Optometrists, Ophthalmologists" },
    { value: "orthopedic_goods_stores", label: "Orthopedic Goods-Artificial Limb Stores" },
    { value: "health_practitioners_medical_services", label: "Health Practitioners, Medical Services-not elsewhere classified" },
    { value: "testing_laboratories", label: "Testing Laboratories-Non medical" },
    { value: "doctors", label: "Doctors-not elsewhere classified" },
  ],
  "housing": [
    { value: "developer", label: "Developer" },
    { value: "facility_management", label: "Facility Management Company" },
    { value: "rwa", label: "RWA" },
    { value: "coworking", label: "Co-working spaces" },
    { value: "realestate_classifieds", label: "Real estate classifieds" },
    { value: "space_rental", label: "Home or office rentals" },
  ],
  "it_and_software": [
    { value: "saas", label: "SaaS (Software as a service)" },
    { value: "paas", label: "Platform as a service" },
    { value: "iaas", label: "Infrastructure as a service" },
    { value: "consulting_and_outsourcing", label: "Consulting and Outsourcing" },
    { value: "web_development", label: "Web designing, development and hosting" },
    { value: "technical_support", label: "Technical Support" },
    { value: "data_processing", label: "Data processing" },
  ],
  "logistics": [
    { value: "freight", label: "Freight Consolidation/Management" },
    { value: "courier", label: "Courier Shipping" },
    { value: "warehousing", label: "Public/Contract Warehousing" },
    { value: "distribution", label: "Distribution Management" },
    { value: "end_to_end_logistics", label: "End-to-end logistics" },
    { value: "courier_services", label: "Courier Services-Air &amp, Ground, Freight Forwarders" },
  ],
  "media_and_entertainment": [
    { value: "video_on_demand", label: "Video on demand" },
    { value: "music_streaming", label: "Music streaming services" },
    { value: "multiplex", label: "Multiplexes" },
    { value: "content_and_publishing", label: "Content and Publishing" },
    { value: "ticketing", label: "Events and movie ticketing" },
    { value: "news", label: "News" },
    { value: "video_game_arcades", label: "Video Game Arcades/Establishments" },
    { value: "video_tape_production_and_distribution", label: "Motion Pictures and Video Tape Production and Distribution" },
    { value: "bowling_alleys", label: "Bowling Alleys" },
    { value: "billiard_and_pool_establishments", label: "Billiard and Pool Establishments" },
    { value: "amusement_parks_and_circuses", label: "Amusement Parks, Carnivals, Circuses, Fortune Tellers" },
    { value: "ticket_agencies", label: "Theatrical Producers-except Motion Pictures, Ticket Agencies" },
  ],
  "not_for_profit": [
    { value: "charity", label: "Charity" },
    { value: "educational", label: "Educational" },
    { value: "religious", label: "Religious" },
    { value: "personal", label: "Personal" },
  ],
  "services": [
    { value: "repair_and_cleaning", label: "Repair and cleaning services" },
    { value: "interior_design_and_architect", label: "Interior Designing and Architect" },
    { value: "movers_and_packers", label: "Movers and Packers" },
    { value: "legal", label: "Legal Services" },
    { value: "event_planning", label: "Event planning services" },
    { value: "service_centre", label: "Service Centre" },
    { value: "consulting", label: "Consulting Services" },
    { value: "ad_and_marketing", label: "Ad and marketing agencies" },
    { value: "services_classifieds", label: "Services Classifieds" },
    { value: "multi_level_marketing", label: "Multi-level Marketing" },
    { value: "construction_services", label: "GENERAL CONTRACTORS" },
    { value: "architectural_services", label: "Horticultural and Landscaping Services" },
    { value: "car_washes", label: "CAR WASHES" },
    { value: "motor_home_rentals", label: "A MOTOR HOME AND RECREATIONAL" },
    { value: "stenographic_and_secretarial_support_services", label: "Stenographic and Secretarial Support Services" },
    { value: "chiropractors", label: "Chiropractors" },
    { value: "automotive_service_shops", label: "Automotive Service Shops" },
    { value: "shoe_repair_shops", label: "Hat Cleaning Shops, Shoe Repair Shops, Shoe Shine Parlors" },
    { value: "telecommunication_service", label: "Telecom Servc including but not ltd to prepaid phone serv" },
    { value: "fines", label: "FINES" },
    { value: "security_agencies", label: "Agencies ‚Äì Security Services" },
    { value: "type_setting_and_engraving_services", label: "Typesetting, Plate Making, Related Services" },
    { value: "small_appliance_repair_shops", label: "Appliance Repair Shops, Electrical and Small" },
    { value: "photography_labs", label: "Photo Developing, Photofinishing Laboratories" },
    { value: "dry_cleaners", label: "Dry Cleaners" },
    { value: "electronic_repair_shops", label: "Electronic Repair Shops" },
    { value: "cleaning_and_sanitation_services", label: "Specialty Cleaning, Polishing, and Sanitation Preparations" },
    { value: "nursing_care_facilities", label: "Nursing and Personal Care Facilities" },
    { value: "direct_marketing", label: "Direct Marketing Other Direct Marketers not elsewhere classified" },
    { value: "veterinary_services", label: "Veterinary Services" },
    { value: "affliated_auto_rental", label: "AFFILIATED AUTO RENTAL" },
    { value: "alimony_and_child_support", label: "COURT COST INCLUDING ALIMONY AND CHILD SUPPORT" },
    { value: "airport_flying_fields", label: "AIRPORT FLYING FIELDS" },
    { value: "tire_retreading_and_repair_shops", label: "Tire Retreading and Repair Shops" },
    { value: "television_cable_services", label: "Cable and other Pay Television Services" },
    { value: "recreational_and_sporting_camps", label: "Recreational and Sporting Camps" },
    { value: "agricultural_cooperatives", label: "AGRICULTURAL COOPERATIVES" },
    { value: "carpentry_contractors", label: "Carpentry Contractors" },
    { value: "wrecking_and_salvaging_services", label: "Wrecking and Salvage Yards" },
    { value: "automobile_towing_services", label: "Towing Services" },
    { value: "barber_and_beauty_shops", label: "Barber and Beauty Shops" },
    { value: "video_tape_rental_stores", label: "Video Tape Rental Stores" },
    { value: "golf_courses", label: "Golf Courses, Public" },
    { value: "miscellaneous_repair_shops", label: "Miscellaneous Repair Shops and Related Services" },
    { value: "motor_homes_and_parts", label: "MOTOR HOME DEALERS" },
    { value: "debt_marriage_personal_counseling_service", label: "Debt, Marriage, Personal Counseling Service" },
    { value: "air_conditioning_and_refrigeration_repair_shops", label: "Air Conditioning and Refrigeration Repair Shops" },
    { value: "tailors", label: "Alterations, Mending, Seamstresses, Tailors" },
    { value: "massage_parlors", label: "Massage Parlors" },
    { value: "horse_or_dog_racing", label: "Government Licensed Horse/Dog Racing" },
    { value: "credit_reporting_agencies", label: "Consumer Credit Reporting Agencies" },
    { value: "heating_and_plumbing_contractors", label: "Air Conditioning, Heating, and Plumbing Contractors" },
    { value: "electrical_contractors", label: "ELECTRICAL CONTRACTORS" },
    { value: "carpet_and_upholstery_cleaning_services", label: "Carpet and Upholstery Cleaning" },
    { value: "roofing_and_metal_work_contractors", label: "Roofing and Siding, Sheet Metal Work Contractors" },
    { value: "internet_service_providers", label: "Computer Network/Information Services" },
    { value: "laundry_services", label: "Cleaning, Garment, and Laundry Services" },
    { value: "recreational_camps", label: "Trailer Parks and Campgrounds" },
    { value: "masonry_contractors", label: "Insulation, Masonry, Plastering, Stonework, and Tile Setting Contractors" },
    { value: "exterminating_and_disinfecting_services", label: "Exterminating and Disinfecting Services" },
    { value: "ambulance_services", label: "Ambulance Services" },
    { value: "funeral_services_and_crematories", label: "Funeral Services and Crematories" },
    { value: "metal_service_centres", label: "Metal Service Centers and Offices" },
    { value: "copying_and_blueprinting_services", label: "Quick Copy, Reproduction, and Blueprinting Services" },
    { value: "fuel_dispensers", label: "Fuel Dispenser, Automated" },
    { value: "lottery", label: "Government Owned Lottery,Government Owned Lottery" },
    { value: "welding_repair", label: "WELDING REPAIR" },
    { value: "mobile_home_dealers", label: "Mobile Home Dealers" },
    { value: "concrete_work_contractors", label: "CONCRETE WORK CONTRACTORS" },
    { value: "boat_rentals", label: "Boat Leases and Boat Rentals" },
    { value: "personal_shoppers_and_shopping_clubs", label: "Buying/Shopping Clubs, Services" },
    { value: "door_to_door_sales", label: "DOOR-TO-DOOR SALES" },
    { value: "travel_related_direct_marketing", label: "Direct Marketing-Travel-Related Arrangement Services" },
    { value: "lottery_and_betting", label: "Betting -including Lottery Tickets, Chips at Gaming Casinos, Off-Track Betting and Wagers at Race Tracks" },
    { value: "bands_orchestras_and_miscellaneous_entertainers", label: "Bands, Orchestras, and Miscellaneous Entertainers-not elsewhere classified" },
    { value: "furniture_repair_and_refinishing", label: "Furniture-Reupholstery and Repair, Refinishing" },
    { value: "direct_marketing_and_subscription_merchants", label: "Direct Marketing-Continuity/Subscription Merchants" },
    { value: "typewriter_stores_sales_service_and_rentals", label: "Typewriter Stores-Sales, Service, and Rentals" },
    { value: "direct_marketing_insurance_services", label: "Direct Marketing-Insurance Services" },
    { value: "business_services", label: "Business Services-not elsewhere classified" },
    { value: "inbound_telemarketing_merchants", label: "Direct Marketing-Inbound Telemarketing Merchants" },
    { value: "recreation_services", label: "Recreation Services-not elsewhere classified" },
    { value: "swimming_pools", label: "Swimming Pools-Sales and Supplies" },
    { value: "outbound_telemarketing_merchants", label: "Direct Marketing-Outbound Telemarketing Merchants" },
    { value: "public_warehousing", label: "Public Warehousing-Farm Products, Refrigerated Goods," },
    { value: "clothing_rental_stores", label: "Clothing Rental-Costumes, Uniforms, and Formal Wear" },
    { value: "contractors", label: "Contractors, Special Trade-not elsewhere classified" },
    { value: "transportation_services", label: "Transportation Services-not elsewhere classified" },
    { value: "electric_razor_stores", label: "Electric Razor Stores-Sales and Service" },
    { value: "service_stations", label: "Service Stations with or without Ancillary Services" },
    { value: "photographic_studio", label: "Photographic studios" },
    { value: "professional_services", label: "Professional services" },
  ],
  "social": [
    { value: "matchmaking", label: "Dating and Matrimony platforms" },
    { value: "social_network", label: "Social Network" },
    { value: "messaging", label: "Messaging and Communication" },
    { value: "professional_network", label: "Professional Network" },
    { value: "neighbourhood_network", label: "Local/Neighbourhood network" },
    { value: "automobile_associations_and_clubs", label: "Automobile Associations" },
    { value: "political_organizations", label: "Political Organizations" },
    { value: "country_and_athletic_clubs", label: "Clubs-Country Clubs, Membership-Athletic, Recreation, Sports, Private Golf Courses" },
    { value: "associations_and_membership", label: "Associations and membership" },
  ],
  "tours_and_travel": [
    { value: "aviation", label: "Aviation" },
    { value: "accommodation", label: "Lodging and Accommodation" },
    { value: "ota", label: "OTA" },
    { value: "travel_agency", label: "Tours and Travel Agency" },
    { value: "tourist_attractions_and_exhibits", label: "Tourist Attractions and Exhibits" },
    { value: "aquariums_dolphinariums_and_seaquariums", label: "Aquariums, Dolphinariums, and Seaquariums" },
    { value: "timeshares", label: "Timeshares" },
  ],
  "transport": [
    { value: "cab_hailing", label: "Cab/auto hailing" },
    { value: "bus", label: "Bus ticketing" },
    { value: "train_and_metro", label: "Train and metro ticketing" },
    { value: "automobile_rentals", label: "National Car Rental" },
    { value: "cruise_lines", label: "CRUISE LINES" },
    { value: "parking_lots_and_garages", label: "Automobile Parking Lots and Garages" },
    { value: "bridge_and_road_tolls", label: "BRIDGE &amp, ROAD FEES, TOLLS" },
    { value: "freight_transport", label: "Railroads and Freight" },
    { value: "truck_and_utility_trailer_rentals", label: "Truck and Utility Trailer Rentals" },
    { value: "transportation", label: "Transportation‚ÄîSuburban and Local Commuter Passenger, including Ferries" },
  ],
  "utilities": [
    { value: "electricity", label: "Electricity" },
    { value: "gas", label: "Gas" },
    { value: "telecom", label: "Telecom Service Provider" },
    { value: "water", label: "Water" },
    { value: "cable", label: "Cable operator" },
    { value: "broadband", label: "Broadband" },
    { value: "dth", label: "DTH" },
    { value: "internet_provider", label: "Internet service provider" },
    { value: "bill_and_recharge_aggregators", label: "Bill Payment and Recharge Aggregators" },
  ],
};

/** Typical default for schools / fee collection orgs. */
export const RAZORPAY_ROUTE_DEFAULT_CATEGORY = "education" as const;

export const RAZORPAY_ROUTE_DEFAULT_SUBCATEGORY = "schools" as const;
